apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memphis-consumer
  template:
    metadata:
      labels:
        app: memphis-consumer
    spec:
      containers:
      - name: memphis-consumer
        image: {{ $.Values.werf.image.consumer }}
        envFrom:
        - configMapRef:
            name: "common-config"
        - secretRef:
            name: "secret"
        env:
        - name: PYTHONUNBUFFERED
          value: "1"