apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: consumer
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-kube-prometheus-prometheus.default.svc.cluster.local:9090
        metricName: memphis_consumer_num_pending
        threshold: "10"
        query: memphis_consumer_num_pending{consumer_name="consumers", stream_name="default$1"}
